started q3
NSS-Full-Time-Data-Analytics-10/lahman_baseball-heartland pull request #10
Opened 2023-06-07 16:53 UTC by april1365

Please review.

2023-06-07 16:55 UTC, chase-payne requested changes
Should we limit this to just one answer and convert sum to money?

2023-06-07 18:21 UTC, tigisttaylor requested changes
The code is good, but to answerer the last part of the question you should have the name of the player below the code.

2023-06-07 19:17 UTC, thecourtneywebb reviewed
looks great!
for consideration rename sum column?
salary to money?
results as 1 row or 2 queries?

2023-06-07 20:46 UTC, chase-payne approved these changes

2023-06-09 14:04 UTC, thecourtneywebb approved these changes

2023-06-09 14:10 UTC, tigisttaylor approved these changes

2023-06-09 14:11 UTC, merged